# Generated by Django 4.0 on 2021-12-15 12:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='picture',
            field=models.ImageField(default=datetime.datetime(2021, 12, 15, 12, 21, 54, 248475, tzinfo=utc), editable=False, upload_to='images'),
            preserve_default=False,
        ),
    ]
