# Generated by Django 4.0 on 2021-12-15 10:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import stories.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('posted_on', models.DateTimeField(auto_now_add=True)),
                ('story_image', models.ImageField(default='story.png', upload_to=stories.models.story_file_path)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_story', to='user.user')),
                ('tagged', models.ManyToManyField(blank=True, related_name='story_tagged', to=settings.AUTH_USER_MODEL)),
                ('views', models.ManyToManyField(blank=True, related_name='story_viewers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-posted_on'],
            },
        ),
    ]
